apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-pod
  namespace: default
spec:
  containers:
    - name: insecure-container
      image: nginx:latest
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        readOnlyRootFilesystem: false
      env:
        - name: DATABASE_PASSWORD
          value: "SuperSecretPassword123"
  networkPolicy: {}
